version: '3'
services:
  web:
    user: node

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_COMPOSE_VERSION: 1.25.4

    environment:
      PORT: 3001
      POSTGRES_HOST: postgres
      DB_PORT: 5432
      DB_TYPE: postgres
      DB_NAME: nba_db
      POSTGRES_USER: caslash
      POSTGRES_PWD: 1212

    volumes:
      - vscode-server-extensions:/home/node/.vscode-server/extensions
      - vscode-server-insiders-extensions:/home/node/.vscode-server-insiders/extensions
      - bash-history:/commandhistory
      - node-modules:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached

    command: sleep infinity

volumes:
  global-node-modules:
  node-modules:
  bash-history:
  vscode-server-extensions:
  vscode-server-insiders-extensions:
